# -*- coding: utf-8 -*-
"""Sumamatrices.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzRxFeiM0vS5Ed278cRvJNbZh9hUvG8y
"""

matriz1=[]
matriz2=[]
matrizResultado=[]
 
print("Matriz 3*3")
for a in range(3):
    matriz1.append([])
    matriz2.append([])
    matrizResultado.append([])
 
for a in range(3):
    for b in range(3):
        matriz1[a].append(input("Ingresar valor de la primera matriz: "))
 
for c in range(3):
    for d in range(3):
        matriz2[c].append(input("Ingresar valor de la segunda matriz: "))
 
for a in range(3):
    for b in range(3):
        matrizResultado[a].append( matriz1[a][b] + matriz2[a][b] )
 
print (matriz1)
print (matriz2)
print (matrizResultado)

3yu
fs333

